### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rabbibotton** [rabbibotton/clog#1]
I am looking for suggestions on ways to make CLOG "feel" lispy - let me know!

**Comment by Inc0ns1st3nt** [comment]
What I learned from some Emacs packages, is that they use '--' instead of '-' notation between "<pkg-name>--<function name>" to distinguish between public and private function, you can use this practice if you want

**Comment by Inc0ns1st3nt** [comment]
what i spotted through out the project, is that there are a lot of repeated code pattern of defining functions of accessor and setter of fields for various objects, some of them can be simplified with macro (defmacro), if you wish.
Such as in clog-form.lisp, there are encoding, autocomplete, placeholder, name.... fields that I would say could definitely benefit on using macros. and with some extra tweaking, it could be more generic to use to generate all of those fields.

**Comment by rabbibotton** [comment]
Yes there is actually tons of code that would benefit from the macro touch.

It is actually intentional and part of a project I am working on connected to compile time computing to delay using macros to have a large enough code base for analysis.

There is also a second reason, I often find that software projects that try to make life easier for the programmer to "type" less tend to produce bad APIs in the end. I refactor by hand often and don't mind getting dirty until I am totally happy with what I have and convinced not evolving more then codify that in macros/templates etc.

There is also a third reason, I needed to some physical therapy on my right hand to improve and refine motor skills and typing out all the code has worked wonderful :)

**Comment by ramenbytes** [comment]
> What I learned from some Emacs packages, is that they use '--' instead of '-' notation between "--" to distinguish between public and private function, you can use this practice if you want

I'd suggest just using Common Lisp's package functionality for that. The if you have a private function in the CLOG package, you'd access it with `clog::<symbol-name>` whereas public symbols would be accessed via `clog:<symbol-name>`. Emacs Lisp doesn't have a package system the way Common Lisp does (though they do have things they call packages), so you have to use `-` and `--` to convey the same information.

**Comment by ramenbytes** [comment]
> I am looking for suggestions on ways to make CLOG "feel" lispy - let me know!

One thing that strikes me is how nice it would be to have more introspection and reflection capabilities, perhaps with some REPL integration. For example, I'm toying with `clog-gui` right now and saw how you added the class "w3-cyan" to the body element in tutorial 22 to change the window color. My immediate thought is "how do I know what classes have been applied to this object?" Being able to do something like `(w3-classes body)` to list out all the applied classes would come in handy later when I wanted to undo experimental stuff. In general, just being able to determine all the properties and state of the gui via convenient Lisp snippets.

Also, being inspector-friendly. When I open up the inspector on a clog object, it looks like there is only really bookkeeping info stored, such as mutexes, connection IDs, and so on, and not much info about the child elements that are contained. I was expecting that I'd be able to inspect the top-level body, and then from there drill down into each element poking around to see what it contains and what it's properties are.

One last thing that comes to mind, which is probably closer to an enhancement, would be to have a way for programmers to 'import' things back from the browser to the REPL. For example, I see a button element and I want to get my hands on it in the REPL to mess around with. Right click the button, select 'Copy object to REPL', and see the object pop up in my REPL buffer ready to play (sly has stuff that could help, I don't know about slime). Basically, making stuff displayed on the webpage closer to actual Lisp objects that we can do all our usual Lispy stuff with. The general feeling I get overall from CLOG is a bit Forth-y at times: in Forth it is pretty easy to interactively move forward and create new things, but more difficult to backtrack and change previous work (at least in my experience with FlashForth and AmForth defaults). Whereas in Lisp, almost everything is easily changed.

Now, all of what I said is based on my subjective impressions of the project so far. Maybe I missed some stuff because I'm new to both CLOG and web programming. I just took note of the friction points where CLOG diverges from my usual expectations of Lisp development given my previous experiences (outside of CLOG and web programming). Other Lispers may feel differently. Also, I definitely think CLOG is neat. I had a big grin on my face when I ran `(setf (background-color *body*) "blue")` and saw the browser update immediately. Very neat stuff overall, and I hope I'll be able to use and contribute to CLOG sometime. Thanks for all your hard work creating it. :)

**Comment by rabbibotton** [comment]
Thank you! Once I am done with 1.0 (getting there) I will pick through and prioritize much if what you wrote to see what can be added. I hope you enjoy clog enough to try your hand at adding to it as well!

**Comment by ramenbytes** [comment]
Cool. Some other Lispers you might want to ask for input include mikelevins and lispm, both of which have extensive experience with Lispy GUIs and interfaces if I recall correctly.

**Comment by Xact** [comment]
I know the objective of clog is to free the user of javascript, but inevitably common lisp users are going to want to dabble... So it might be nice to have a function for providing raw js via the :content keyword. I have implemented a function called js-to-str which fits like so: (concatenate 'string (js-to-str "myRawJS_1") (js-to-str "anotherJSfile")). 
NB- postfix '.js' omitted from filename.

Here is the code for js-to-str and file-to-string (I'm sure I've duplicated something from one of the libraries but this works, so... whatever ;) 

(defun js-to-str (filename &key (format "js"))
  (file-to-string (concatenate 'string
                                    "/Home/path/"
                                    filename
                                    "."
                                    format)))


(defun file-to-string (file-path)
  (let ((s (MAKE-STRING-OUTPUT-STREAM))
        (output nil))
    (with-open-file (f file-path :direction :input)
      (let ((line nil) (eof nil))
        (with-standard-io-syntax
          (loop for l = (setf (values line eof) (read-line f nil nil))
             while l do (progn (format s "~&~A" line)
                               (unless eof (format s "~%")))))))
    (format nil "~A~%~%" (GET-OUTPUT-STREAM-STRING s))))

**Comment by jonprairie** [comment]
First off: I've been playing around with clog and it's been awesome so far, so thanks for all your work! I've had a couple thoughts:
1. The document generation seems kinda clunky. I'd really like to have something like spinneret integrated to generate the html (so far I've just been SETFing the inner-html of body to a spinneret:with-html-string call, but this doesn't feel great)
2. Somewhat related: attaching to existing html is also clunky; as far as I can tell it's only supported by id. It'd be nice to also have access to a class selector (full css selectors would be amazing) so I could, for instance, grab a list of all the elements of a certain class, then loop through and assign them all to the same on-click handler.

**Comment by rabbibotton** [comment]
CLOG is about the browser as a "screen" not a document. While it can be used like any web framework and I will look to add some features to make document serving more convenient, I purposely have left that out to start with to not allow CLOG to derail in to just another web "page" app. I am working on some mid-level additions to CLOG now, like "panels" and alternative layout of "widgets/controls" things and that will help illustrate that also, but I will though add some doc serving in its time :)

**Comment by fbmnds** [comment]
@rabbibotton  You may find it interesting that I am in process to convert an existing React web app into a CLOG app. The interesting part I came across is that is possible to combine SSR/CLOG and and CSR/React in the same application.

For injecting state into React components from the server-side code, the trick is to expose React hooks as globally availabe Javascript functions that allow to toggle state in React components, ref. e.g. [here](https://bitbucket.org/fbmnds7/relays-ui/commits/9cd3aa8364c0404a50d6b7b9de91293b93cd884d). 

It really works, as the following screenshot confirms:
![clog-to-react](https://user-images.githubusercontent.com/1843282/144306203-8e1e3396-1d4f-4c0b-9ef9-76e3dfc30375.jpg)

If I want to switch from client-side code to the server, it would be possible use the event handler of a hidden CLOG container (`create-div`), or simply using a REST endpoint which could easily be added to the app.  

Given your last comment on this isse, I do not think that you like this idea :-) but I find it really exiting.

**Comment by rabbibotton** [comment]
I am not against at all, in fact it is amazing in that capacity. I am just not focusing on it as people will lose track of what CLOG can do or ignore it an thinking it is an "ajax" alternative.

**Comment by maxz** [comment]
Is it currently possible to interact with canvas objects? (e. g. register a click on a line)
The current examples do not cover this so I'm not sure. Tutorial 10 has this kind of output but no interactivity.

I would like to draw some elements and when clicking them have other elements pop up or information displayed (e. g. via a mouseover text).

**Comment by rabbibotton** [comment]
The HTML canvas is a dumb bit buffer, so no. However what I have done in the past is make lots of canvases with positioning set to :absolute only draw say a line, figure etc, and can add events etc to it.
