### ISSUE TITLE
Bug: Unable to setf text-value of a clog element

### ISSUE THREAD

**Issue by imadhui** [rabbibotton/clog#230]
This is the code to reproduce the bug:

```
(ql:quickload :clog)

(in-package :clog-user)

(clog-repl)

(defparameter *div* (create-div *body* :content ""))

(setf (text-value *div*) "d")

```

Nothing shows up on the browser. The browser console shows an error. This is from safari.

![image](https://user-images.githubusercontent.com/111036389/189465258-11b23c5e-6e12-4ea6-ad43-3d25a1f10ace.jpeg)

The bug is also reproducible on chrome.

**Comment by imadhui** [comment]
This only happens when `content` is `""` in `create-div`.

**Comment by imadhui** [comment]
This bug has nothing to do with `clog-repl`. I discovered it when I was working on my app.

**Comment by rabbibotton** [comment]
Is a bug with HTML itself. Creating a div with no content produces a div without a text node (technically not part of html). I'll give you some work arounds soon

**Comment by rabbibotton** [comment]
So the official way to place text in a DIV with no text node is

1. Use text (or inner-html) instead of text-value (text-value won't replace the any html if exists with in the div, text will erase anything in the div. keep that in mind)
2. Create it with some text and then replace the text with ""
3. Use place-text-inside-bottom-of or place-text-inside-top-of that create new text nodes.
