### ISSUE TITLE
Create a single Tutorials ASDF system

### ISSUE THREAD

**Issue by svetlyak40wt** [rabbibotton/clog#45]
It would be cool to run:

```
(ql:quickload :clog-tutorials)
(clog-tutorials:start)
```

It should open the web page with the list of all tutorials where I can click and view them all without having to load separate lisp files manually.

**Comment by rabbibotton** [comment]
I want to finish up clog-web and a website demo and then I think that is an excellent idea.

**Comment by rabbibotton** [comment]
I decided not to add the separate asdf for the tutorials as they are not really a demo but a series of steps to work through. Often there are important comments (I just redid tutorial 1 to reflect not using #' on events so can used M-C-x during dev or on tutorial 3 to try an alternative in the code where events are synced with the new WITH-SYNC-EVENT and to see the difference between parallel vs synchronized events.

It may make sense for the DEMOs but I will need to modify them so that each demo runs on a different subdirectory or port. Likely a good idea to use ports but have to look if that is possible with clack/hutchentoot
